### ISSUE TITLE
Highlight bugs regarding quotes (GitHub's highlighter)

### ISSUE THREAD

**Issue by Explorer09** [mmims/language-batchfile#11]
I discovered two bugs on GitHub's batch file highlighting and from [this](https://github.com/github/linguist/blob/master/vendor/README.md) I am recommended to report it here:

[Test code](https://gist.github.com/Explorer09/7ddad79a914f596712eac3b7cce7c135)

    SETLOCAL EnableDelayedExpansion
    REM Stripping quotes from a variable
    SET foo=some^"quoted^"text
    SET bar=!foo:^"=!
    REM ^"

![actual result and expected result](https://cloud.githubusercontent.com/assets/2487263/25556765/806f4412-2d35-11e7-83aa-4080117e69bd.png)

This look like two problems that happen simultaneously in the code above:
1. Escaped quotes are not identified and highlighter still thinks the quoting is still in effect.
2. Highlighter thinks the quote effects cross newlines, but in fact it's not. (Batch is unlike Unix shell, the latter have quotes span newlines)

Because of the bugs, [I worked-around by batch script](https://github.com/Explorer09/usb_vaccine/commit/99c52474c4650cb85814248ae20570e1201f7855).

**Comment by mmims** [comment]
Thanks for reporting your issue @Explorer09. There is very little documentation on the batch language specifications so it is sometimes hard to determine how the syntax should be interpreted. In my experience, there is no need to escape `"` characters when you are setting variables. So the following:
```batch
SET foo=some ^"quoted^" text
SET foo2=some "quoted" text
ECHO %foo%
ECHO %foo2%
```
will produce the same results:
```
some "quoted" text
some "quoted" text
```
However, it appears that the `SET` command does recognize the escape character in that instance so I'll need to look into adding that.

As for the variable substitution, the escape character is not recognized and treated as a literal. So the following:
```batch
SET bar=%foo:^"=%
SET bar2=%foo:"=%
ECHO bar
ECHO bar2
```
will produce different results:
```
some "quoted" text
some quoted text
```
Again this is still an issue with the parser that will need to be investigated, but I did want to point out that it is a case of the escape character not being recognized.

**Comment by Explorer09** [comment]
@mmims I have been writing batch language so long that I often bump into the limits of the language. Yes, I know the language is not documented so well, but with some testing it's still possible to determine the syntax and grammar. I report this issue because I've tested out that **quotes effect does not wrap over newlines** and so this highlighter reads the syntax wrong.

Here's more:

> In my experience, there is no need to escape " characters when you are setting variables.
> So the following:
>     SET foo=some ^"quoted^" text
>     SET foo2=some "quoted" text
>     ECHO %foo%
>     ECHO %foo2%
> will produce the same results:
>     some "quoted" text
>     some "quoted" text

Not if you put some carets or special characters in the quoted text. This example will show the difference:

    SET foo=foo "bar & ^ %% baz" something
    SET foo2=foo ^"bar ^& dir ^& ^^ %% baz^" something
    REM A DIR command will be executed at the SET foo3 line.
    REM With the & unquoted and unescaped, it terminates the SET line and
    REM executes the command after that.
    SET foo3=foo ^"bar & dir & echo baz^" something
    ECHO %foo%
    REM foo2 need to be delay-expanded to be safe, because the text contains &.
    REM (or you may try %foo2% and see DIR command executed while
    REM expanding -- this is the longstanding batch command injection vulnerability.)
    ECHO !foo2!

Expected output:

    foo "bar & ^ % baz" something
    foo "bar & dir & ^ % baz" something

**Comment by Explorer09** [comment]
@mmims
(continued)

> As for the variable substitution, the escape character is not recognized and treated as a literal. So the following:
> ```
> SET bar=%foo:^"=%
> SET bar2=%foo:"=%
> ECHO bar
> ECHO bar2
> ```
> will produce different results:
> ```
> some "quoted" text
> some quoted text
> ```
> Again this is still an issue with the parser that will need to be investigated, but I did want to point out that it is a case of the escape character not being recognized.

In batch, percent variable expansion happens before any caret escapes can take effect. So in this case,
the quotes _must not_ be escaped.
With delayed expansion, however, the quotes _must_ be escaped to prevent messing up the interpreter's recognition of quoted text.

In short, write this way, period:
```
SETLOCAL EnableDelayedExpansion
ECHO %foo:"=%
ECHO !foo:^"=!
REM Safe (dir command not executed):
ECHO %foo:"=% "&dir&"
REM Safe (dir command not executed):
ECHO !foo:^"=! "&dir&"
REM Safe only if foo contains no quotes:
SET "bar=%foo%"
REM Always safe:
SET "bar=!foo!"
REM Always safe:
SET ^"bar=!foo:^"=!^"
REM Always safe:
SET bar=!foo:^"=!
```

**Comment by Explorer09** [comment]
![untitled 1](https://cloud.githubusercontent.com/assets/2487263/25731763/eb73458e-317b-11e7-8fa3-2b783eccd8d9.png)

**Comment by mmims** [comment]
I'm working on a major rewrite of the grammar that will address these issues. It might take some time before it is complete, but it is in the works.
