### ISSUE TITLE
Highlight bug regarding new lines

### ISSUE THREAD

**Issue by gtwy** [mmims/language-batchfile#12]
When using DOS formatted text (as batchfiles usually are) there is a glitch that creates a highlighted **^M** at the end of a new line.

The glitch can be reproduced by ending any line of code with :text (a colon followed by at least 2 text characters.)

You can see the bug here: https://github.com/gtwy/Fix-Windows-Time/blob/master/fix_time.bat

**Comment by gtwy** [comment]
I found the offending line:

https://github.com/mmims/language-batchfile/blob/master/grammars/batchfile.cson#L114

I don't know if throwing a \b on the end of that would fix it or not. I am not an expert at regex.

**Comment by mmims** [comment]
You're correct it is incorrectly identifying the argument as a batch label. I'm working on a major rewrite of the grammar that will address this issue.

**Comment by gtwy** [comment]
Thanks. I put in a pull request in the meantime.
