### ISSUE TITLE
Label colour

### ISSUE THREAD

**Issue by hannesfant** [mmims/language-batchfile#15]
So the label is just white and not italic, I don't know if this a bug or not but I think it looked much better when it was italic and coloured.

**Comment by mmims** [comment]
Unfortunately, it is dependent of the theme that you are using as to how it will be handled. The screenshot below is using the Atom Dark theme and it gives labels a nice distinct color.

![labels_capture](https://cloud.githubusercontent.com/assets/534908/26501424/9d1df91e-4207-11e7-9be6-f9cf1eae7e71.PNG)

What syntax theme are you using?

**Comment by hannesfant** [comment]
[Nord Atom syntax. ](https://atom.io/themes/nord-atom-syntax)

**Comment by mmims** [comment]
Alright, I'm going to revert back to the scope I was previously using for labels. I was debating on doing that anyway so I'll go ahead and make that change.
