### ISSUE TITLE
Digits that are part of filenames are highlighted as numbers

### ISSUE THREAD

**Issue by nwhetsell** [mmims/language-batchfile#19]
Digits within filenames appear to be highlighted as numbers, which can look a bit unusual. For example, a snippet for running the current [SourceTree](https://www.sourcetreeapp.com) installer from Command Prompt looks like

```bat
SourceTreeSetup-2.1.2.5
```

The `-2`, `1`, `2`, and `5` in the filename are highlighted as numbers.

**Comment by mmims** [comment]
Thanks for reporting. I will change the way the boundaries are determined for numbers.

**Comment by nwhetsell** [comment]
Awesome, thanks!

I figure I should also mention that a similar issue exists for hyphenated command line options. For example

```bat
latex -output-format pdf file.tex
```

shows `format` highlighted as a keyword.
