### ISSUE TITLE
Syntax highlight broken for Batch file

### ISSUE THREAD

**Issue by aeschli** [mmims/language-batchfile#22]
_From @wlai2768 on January 7, 2018 1:40_

Steps to Reproduce:

1. Open a new file
2. Change file type to Batch file
3. Paste below two lines.  The first "for" line color rendering is broken.

```batch
for %%i in ( %* ) do if "%%i"=="--watch" goto :do_%1_%2_watch
for %%i in ( 
    %* 
) do if "%%i"=="--watch" goto :do_%1_%2_watch
```

_Copied from original issue: Microsoft/vscode#41235_

**Comment by mmims** [comment]
Thanks for submitting. It will be a week or so before I can look at this.

**Comment by Explorer09** [comment]
Off-topic, but has the issue reporter aware that %1 or %* form of expansions are vulnerable to command injection? It's probably a bad idea to place %* to FOR token set unless you (the programmer) have control over what would be inside the %*.

**Comment by mmims** [comment]
I have reviewed this using the latest versions of both Atom and VS Code. Neither editor (nor the github linguist highlighting) produce any noticeable issues. Both lines 1 and 3 look identical.

### VS Code ###
![image](https://user-images.githubusercontent.com/534908/35106171-8654d736-fc3b-11e7-848c-09f2b1ba20ad.png)

- Version 1.19.2
- Commit 490ef761b76b3f3b3832eff7a588aac891e5fe80
- Date 2018-01-10T15:55:03.538Z
- Shell 1.7.9
- Renderer 58.0.3029.110
- Node 7.9.0
- Architecture x64

### Atom ###
![image](https://user-images.githubusercontent.com/534908/35106235-b547c1d4-fc3b-11e7-8d87-8e863bdf016e.png)

- apm  1.18.12
- npm  3.10.10
- node 6.9.5 x64
- atom 1.23.3
- python
- git 2.10.1.windows.1
- visual studio 2015

I suggest that the original submitter @wlai2768 update to the latest version of VS Code.

**Comment by Explorer09** [comment]
@mmims I guess the bug is that `goto` isn't highlighted correctly, and that `%i"=="--watch" goto :` looks like a single token.

Because I can reproduce this with GitHub's highlighter, I can show comparable examples with one highlighted correctly and one broken.
```batch
rem Good:
for %%i in ( foo ) do if "%%i"=="--watch" goto :do_1_2_watch
rem Bad:
for %%i in ( foo ) do if "%%i"=="--watch" goto :do_%1_2_watch
```
![selection_329](https://user-images.githubusercontent.com/2487263/35107867-01e66952-fcad-11e7-832c-50f7a08e3719.png)
