### ISSUE TITLE
[bat] The command `set "flag="` breaks syntax highlighting

### ISSUE THREAD

**Issue by aeschli** [mmims/language-batchfile#23]
_From @DmitrySokolov on February 1, 2018 13:49_

- VSCode Version: Code 1.19.3 (7c4205b5c6e52a53b81c69d2b2dc8a627abaa0ba, 2018-01-25T10:36:34.867Z)
- OS Version: Windows_NT x64 10.0.16299
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
hg|mrc|1.2.3
cpptools|ms-|0.14.6
cmake|twx|0.0.17

(2 theme extensions excluded)

---

Steps to Reproduce:

1. Create test.cmd
```bat
@echo off
setlocal
set "flag="
endlocal

exit /b 0
```

EXPECTED
`endlocal` and the rest of command are highlighted

ACTUAL
`endlocal` and the rest of command have the default font color

Reproduces without extensions: Yes

_Copied from original issue: Microsoft/vscode#42733_

**Comment by DmitrySokolov** [comment]
What is the next actions? Will this fix be merged in VS Code repo? Should I reopen Microsoft/vscode#42733?

**Comment by mmims** [comment]
Are you using the latest version? This fix has been merged into the March 2018 VS Code release (v1.22).

**Comment by DmitrySokolov** [comment]
Nope.

v1.21.1
commit 79b44aa704ce542d8ca4a3cc44cfca566e7720f1
2018-03-14T14:46:47.128Z

I'll check v1.22.

**Comment by DmitrySokolov** [comment]
v1.22.2
commit 3aeede733d9a3098f7b4bdc1f66b63b0f48c1ef9
2018-04-12T16:38:45.278Z

It's fixed. Thanks!
