### ISSUE TITLE
Work together with other batch language

### ISSUE THREAD

**Issue by rugk** [mmims/language-batchfile#3]
Can't you work together with https://github.com/footballhead/language-batch?
So that we have one language-batch.

See https://github.com/footballhead/language-batch/issues/17

**Comment by mmims** [comment]
I never intended to have two separate implementations. It just so happened that we submitted our packages on the same day. Personally, I believe my implementation is a little more robust, but I'm not opposed to consolidating them into one package.

**Comment by mmims** [comment]
Marking this as closed since I haven't heard from the other maintainer. It would appear that he has abandoned the package so I don't know that this will ever be resolved.
