### ISSUE TITLE
Parsing Comment Blocks

### ISSUE THREAD

**Issue by ChaosOrdeal** [mmims/language-batchfile#33]
Text typed as comments in a comment block is being parsed and colored as if it's code.  Not breaking, but for some reason it's annoying me to distraction.

/*
[text here is being parsed/lexed and colored]
*/

**Comment by mmims** [comment]
That is not valid syntax for comments in batch files. There are no multi-line comments. Valid syntax for comments would be:

```batchfile
REM text here is a comment

:: This is another way to comment
:: next line of a comment
```
