### ISSUE TITLE
Echos and quotation marks

### ISSUE THREAD

**Issue by Akaizoku** [mmims/language-batchfile#5]
When echoing something that contains a simple quote ('), the following text is interpreted as a string until it finds another matching simple quote (e.g. `echo It's OK.`).

This breaks all further syntax highlighting.

Could it be possible to ignore simple quote that are part of an echo? Would there be a downside to it?

**Comment by mmims** [comment]
Sorry about the delayed response. I've just been back looking into this issue, and I think I can safely ignore all scopes except for variables for any text that comes after the `echo` keyword. Hopefully, this will resolve the issue. I'll update it shortly. Thanks for reporting the issue.
