### ISSUE TITLE
Parameter Highlight is not as expected

### ISSUE THREAD

**Issue by wolfram77** [mmims/language-batchfile#7]
![image](https://cloud.githubusercontent.com/assets/3179612/18204917/f4c91550-713c-11e6-966a-1b61af09e101.png)

Plugin is considering "%2 %" as a variable.
Hence, it is considering "3 " as text.
Plugin is considering "%4 %" as a variable.
Hence, it is considering "5 " as text.
...

Thanks
Subhajit

**Comment by wolfram77** [comment]
Moving this match pattern to the top of search list might solve it.

```
  {
    'match': '%[\\d\\*]'
    'name': 'variable.other.argument.batchfile'
  }
```

**Comment by mmims** [comment]
You were correct. Re prioritizing the variable search order has resolved this issue. Thanks for reporting it!
