### ISSUE TITLE
Variable string substitution not highlighted as expected.

### ISSUE THREAD

**Issue by wolfram77** [mmims/language-batchfile#8]
![image](https://cloud.githubusercontent.com/assets/3179612/18230307/599f9ef4-72b4-11e6-9d29-adf8418629d5.png)

When using variable string substitution, the highlight is including till the next variable's end "%".
This might get fixed by setting your matcher:

```
      {
        'match': '%[\\w -]+?(:~\\-?\\d+(,\\-?\\d+)?|:.+=.+)?%'
        'name': 'variable.other.environment.batchfile'
      }
```

to this:

```
%[\\w -]+?(:~\\-?\\d+(,\\-?\\d+)?|:.+?=.*?)?%
```

Thanks for fixing the parameter highlight. Sorry for bothering you again.

Thanks
Subhajit

**Comment by mmims** [comment]
Thanks for catching another one. I believe your regex modifications should resolve the issue. An update will be coming shortly.
